web:
  build: .
  volumes:
    - "app:/src/app"
  ports:
    - "80:3000"
  links:
    - "mysql:mysql"
    - "mongodb:mongodb"

mysql:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=qiaojian123
    - MYSQL_DATABASE=ng2admin
  ports:
      - "3306:3306"

mongodb:
  image: mongo
  ports:
      - "27017:27017"
